[XComGame.X2SoldierClass_DefaultClasses]
;Name of your soldier class (IMPORTANT FOR SRC CODES)
+SoldierClasses = "WOTC_Prof_Warden_BD"

[WOTC_Prof_Warden_BD X2SoldierClassTemplate]
bMultiplayerOnly = 0
ClassPoints = 4
bHasClassMovie = false
IconImage = "img:///Warden_BD_PerkIcons.UIIcon_WardenClassNewBW" 
NumInForcedDeck = 1
NumInDeck = 2

; TODO: Set the same as for Ranger / Templar / Prof Assault
KillAssistsPerKill = 4
BaseAbilityPointsPerPromotion = 6

SquaddieLoadout = "SquaddieWarden_BD"
bNoSecondaryWeapon = false
+AllowedWeapons = (SlotType=eInvSlot_PrimaryWeapon,	WeaponType ="bullpup")
+AllowedWeapons = (SlotType=eInvSlot_SecondaryWeapon,	WeaponType ="sword")
+AllowedArmors = "templar"

bCanHaveBonds = true
;if there is a class you want to have a slower bond progression with
; TODO: Add prof assault here
+UnfavoredClasses = "WOTC_Prof_Warden_BD"
+UnfavoredClasses = "WOTC_APA_Assault"
+UnfavoredClasses = "WOTC_APA_Templar"
+UnfavoredClasses = "Ranger"
+UnfavoredClasses = "Templar"

bAllowAWCAbilities = true

+RandomAbilityDecks=( DeckName="WOTC_Prof_Warden_BD_Deck_1", \\
                Abilities=( (AbilityName="TacticalRigging"), \\
							(AbilityName="Warden_BD_Brand"), \\
							(AbilityName="Warden_BD_Combatives"), \\
                            (AbilityName="Warden_BD_Pillar") \\
                    )   )

+RandomAbilityDecks=( DeckName="WOTC_Prof_Warden_BD_Deck_2", \\
                Abilities=( (AbilityName="LightningReflexes"), \\
							(AbilityName="Untouchable"), \\
							(AbilityName="Warden_BD_Inspire"), \\
                            (AbilityName="Warden_BD_Fuse") \\
                    )   )

; TODO: Balance soldier stat growth to be the middle ground between Prof Templar and Prof Assault.

+SoldierRanks=( AbilitySlots=( \\
		(AbilityType=(AbilityName="Warden_BD_Stances")), \\
        (AbilityType=(AbilityName="SwordSlice", ApplyToWeaponSlot=eInvSlot_SecondaryWeapon)), \\
		(AbilityType=(AbilityName="Warden_BD_EbbAndFlowDummy", ApplyToWeaponSlot=eInvSlot_PrimaryWeapon)), \\
		(AbilityType=(AbilityName="Warden_BD_Rewind")) \\
        ), \\
                aStatProgression=( \\
        (StatType=eStat_HP,         StatAmount=1), \\
        (StatType=eStat_Offense,    StatAmount=3), \\
        (StatType=eStat_Will,       StatAmount=5), \\
        (StatType=eStat_Strength,   StatAmount=0), \\
        (StatType=eStat_Dodge,      StatAmount=2), \\
        (StatType=eStat_Hacking,    StatAmount=0), \\
        (StatType=eStat_CombatSims, StatAmount=1), \\
		(StatType=eStat_PsiOffense, StatAmount=40), \\
        )       )

+SoldierRanks=( AbilitySlots=( \\
        (AbilityType=(AbilityName="Warden_BD_GrantImbueAmmoCharges", ApplyToWeaponSlot=eInvSlot_PrimaryWeapon)), \\
        (AbilityType=(AbilityName="Warden_BD_GrantSoulBladeCharges", ApplyToWeaponSlot=eInvSlot_SecondaryWeapon)), \\
        (AbilityType=(AbilityName="Warden_BD_Mirror")), \\
        (RandomDeckName="WOTC_Prof_Warden_BD_Deck_1") \\
        ), \\
                aStatProgression=( \\
        (StatType=eStat_HP,         StatAmount=1), \\
        (StatType=eStat_Offense,    StatAmount=3), \\
        (StatType=eStat_Will,       StatAmount=3), \\
        (StatType=eStat_Strength,   StatAmount=1), \\
        (StatType=eStat_Dodge,      StatAmount=1), \\
        (StatType=eStat_Hacking,    StatAmount=0), \\
		(StatType=eStat_PsiOffense, StatAmount=6, RandStatAmount=6, CapStatAmount=100), \\
        )       )

+SoldierRanks=( AbilitySlots=( \\
        (AbilityType=(AbilityName="Warden_BD_DefenderPassive")), \\
		(AbilityType=(AbilityName="Warden_BD_Momentum")), \\
        (AbilityType=(AbilityName="Warden_BD_WatcherPassive")), \\
        (RandomDeckName="WOTC_Prof_Warden_BD_Deck_1") \\
        ), \\
                aStatProgression=( \\
        (StatType=eStat_HP,         StatAmount=1), \\
        (StatType=eStat_Offense,    StatAmount=2), \\
        (StatType=eStat_Will,       StatAmount=2), \\
        (StatType=eStat_Strength,   StatAmount=0), \\
        (StatType=eStat_Dodge,      StatAmount=2), \\
        (StatType=eStat_Hacking,    StatAmount=2), \\
		(StatType=eStat_PsiOffense, StatAmount=6, RandStatAmount=6, CapStatAmount=100), \\
        )       )

+SoldierRanks=( AbilitySlots=( \\
        (AbilityType=(AbilityName="Warden_BD_RagePassive", ApplyToWeaponSlot=eInvSlot_PrimaryWeapon)), \\
        (AbilityType=(AbilityName="Warden_BD_Tide", ApplyToWeaponSlot=eInvSlot_SecondaryWeapon)), \\
        (AbilityType=(AbilityName="Warden_BD_Consume", )), \\
        (RandomDeckName="WOTC_Prof_Warden_BD_Deck_1") \\
        ), \\
                aStatProgression=( \\
        (StatType=eStat_HP,         StatAmount=1), \\
        (StatType=eStat_Offense,    StatAmount=2), \\
        (StatType=eStat_Will,       StatAmount=2), \\
        (StatType=eStat_Strength,   StatAmount=0), \\
        (StatType=eStat_Dodge,      StatAmount=1), \\
        (StatType=eStat_Hacking,    StatAmount=1), \\
		(StatType=eStat_PsiOffense, StatAmount=6, RandStatAmount=6, CapStatAmount=100), \\
        )       )

+SoldierRanks=( AbilitySlots=( \\
        (AbilityType=(AbilityName="Warden_BD_DefensiveWard", ApplyToWeaponSlot=eInvSlot_PrimaryWeapon)), \\
        (AbilityType=(AbilityName="Warden_BD_Fissure", ApplyToWeaponSlot=eInvSlot_PrimaryWeapon)), \\
        (AbilityType=(AbilityName="Warden_BD_Retribution", ApplyToWeaponSlot=eInvSlot_PrimaryWeapon)), \\
        (RandomDeckName="WOTC_Prof_Warden_BD_Deck_2") \\
        ), \\
                aStatProgression=( \\
        (StatType=eStat_HP,         StatAmount=0), \\
        (StatType=eStat_Offense,    StatAmount=2), \\
        (StatType=eStat_Will,       StatAmount=3), \\
        (StatType=eStat_Strength,   StatAmount=1), \\
        (StatType=eStat_Dodge,      StatAmount=2), \\
        (StatType=eStat_Hacking,    StatAmount=1), \\
		(StatType=eStat_PsiOffense, StatAmount=6, RandStatAmount=6, CapStatAmount=100), \\
        )       )

+SoldierRanks=( AbilitySlots=( \\
        (AbilityType=(AbilityName="Warden_BD_StanceUnity")), \\
        (AbilityType=(AbilityName="Warden_BD_BattleRhythm")), \\
        (AbilityType=(AbilityName="Warden_BD_FlowFocusPassive")), \\
        (RandomDeckName="WOTC_Prof_Warden_BD_Deck_2") \\
        ), \\
                aStatProgression=( \\
        (StatType=eStat_HP,         StatAmount=1), \\
        (StatType=eStat_Offense,    StatAmount=1), \\
        (StatType=eStat_Will,       StatAmount=2), \\
        (StatType=eStat_Strength,   StatAmount=0), \\
        (StatType=eStat_Dodge,      StatAmount=1), \\
        (StatType=eStat_Hacking,    StatAmount=1), \\
		(StatType=eStat_PsiOffense, StatAmount=8, RandStatAmount=6, CapStatAmount=100), \\
        )       )

+SoldierRanks=( AbilitySlots=( \\
        (AbilityType=(AbilityName="Warden_BD_FractureRanged", ApplyToWeaponSlot=eInvSlot_PrimaryWeapon)), \\
        (AbilityType=(AbilityName="Warden_BD_LastRites", ApplyToWeaponSlot=eInvSlot_SecondaryWeapon)), \\
        (AbilityType=(AbilityName="Warden_BD_Charge")), \\
        (RandomDeckName="WOTC_Prof_Warden_BD_Deck_2") \\
        ), \\
                aStatProgression=( \\
        (StatType=eStat_HP,         StatAmount=1), \\
        (StatType=eStat_Offense,    StatAmount=1), \\
        (StatType=eStat_Will,       StatAmount=3), \\
        (StatType=eStat_Strength,   StatAmount=0), \\
        (StatType=eStat_Dodge,      StatAmount=1), \\
        (StatType=eStat_Hacking,    StatAmount=1), \\
		(StatType=eStat_PsiOffense, StatAmount=8, RandStatAmount=6, CapStatAmount=100), \\
        )       )
