[WOTC_Prof_Warden_BD.X2Effect_WardenCounterDefense]
;Note this is the percentage of cover defense negated (e.g. If an enemy is in high cover, giving a 40% aim penalty, this would be reduced to a 20% penalty when CDEF_BONUS = 50)
RANGEDSTANCE_I_CDEF_BONUS = 25
RANGEDSTANCE_II_CDEF_BONUS = 37.5
RANGEDSTANCE_III_CDEF_BONUS = 50

[WOTC_Prof_Warden_BD.X2Ability_Warden]

RANGEDSTANCE_I_CRIT_BONUS = 5
RANGEDSTANCE_II_CRIT_BONUS = 10
RANGEDSTANCE_III_CRIT_BONUS = 10

WARDENSSWORD_AIM_I_BONUS = 5
WARDENSSWORD_AIM_II_BONUS = 10
WARDENSSWORD_AIM_III_BONUS = 10

MELEESTANCE_I_MOBILITY_BONUS = 2
MELEESTANCE_II_MOBILITY_BONUS = 3
MELEESTANCE_III_MOBILITY_BONUS = 4

RANGEDSTANCE_AIM_PENALTY = 10
MELEESTANCE_AIM_PENALTY = 10

FLOW_MASTERY_BASE_CHARGES = 1
FLOW_MASTERY_CHARGE_INCREASE = 1
MOMENTUM_COOLDOWN = 3

MIRROR_NUMBER_OF_ATTACKS = 2
MIRROR_COOLDOWN = 3
MIRROR_RETURN_FULL_DAMAGE = true

REWIND_COOLDOWN = 3

CRUSADER_AIM_BONUS = 5
CRUSADER_CRIT_BONUS = 10

SOULBLADE_COOLDOWN = 2
SOULBLADE_DAMAGE_BONUS = 3
SOULBLADE_INITIAL_CHARGES = 1

IMBUEAMMO_COOLDOWN = 2
IMBUEAMMO_DAMAGE_BONUS = 3
IMBUEAMMO_INITIAL_CHARGES = 1
IMBUEAMMO_ENVDAMAGE = 75

DEFENSIVE_WARD_COOLDOWN = 4
DEFENSIVE_WARD_RANGE = 12

DEFENSIVE_WARD_INITIAL_DAMAGE = 3
DEFENSIVE_WARD_INITIAL_SPREAD = 1

DEFENSIVE_WARD_RADIUS_METERS = 5
DEFENSIVE_WARD_INITIAL_RANGE = 12
DEFENSIVE_WARD_DISORIENT_TURNS = 2

DEFENSIVE_WARD_DAMAGE = 6
DEFENSIVE_WARD_SPREAD = 0

MELEE_COUNTERATTACK_DODGE_AMOUNT = 100
RANGED_COUNTERATTACK_DODGE_AMOUNT = 100
MAX_COUNTERATTACKS_ALLOWED = 2

FISSURE_COOLDOWN = 4
FISSURE_RADIUS_METERS = 5
FISSURE_RANGE = 12

FISSURE_INITIAL_AMOUNT = 1
FISSURE_AMOUNT = 3

TIDE_COOLDOWN = 3
TIDE_DAMAGE_AMOUNT = 3
TIDE_ENVDAMAGE = 10
TIDE_STUN_TURNS = 1
TIDE_KNOCKBACK_DISTANCE = 3
TIDE_RADIUS_METERS = 6

CONSUME_COOLDOWN = 3
CONSUME_RADIUS_METERS =  5
CONSUME_RANGE = 12

RETRIBUTION_COOLDOWN = 4
RETRIBUTION_RADIUS_METERS = 5
RETRIBUTION_RANGE = 12

BRAND_OFFENSE_STAT_BONUS = 10
BRAND_DAMAGE_BONUS = 1
BRAND_CRIT_DAMAGE_BONUS = 1
BRAND_COOLDOWN = 3

PILLAR_COOLDOWN = 3
PILLAR_DURATION = 3

FUSE_COOLDOWN = 2
INSPIRE_COOLDOWN = 3

FLOWFOCUS_COOLDOWN = 6
BATTLE_RHYTHM_MAX_CHARGES = 2
CHARGE_COOLDOWN = 6

FRACTURE_RANGED_COOLDOWN = 8
FRACTURE_RANGED_BULLET_CHARGES = 2

LAST_RITES_COOLDOWN=8
LAST_RITES_SOULBLADE_CHARGES=2
LAST_RITES_DURATION=3
LAST_RITES_DAMAGE_BONUS=1

CHARGE_NUMPOINTS = 3

[WOTC_Prof_Warden_BD.X2Effect_EbbAndFlowDischarge]
EBB_FLOW_DISCHARGE_SCALAR = 20

[WOTC_Prof_Warden_BD.X2Effect_WardenConsumeDamage]
CONSUME_DAMAGE_MULTIPLIER = 1

[WOTC_Prof_Warden_BD.WardenGTSUnlocks]
CLASS_UNLOCK_1_COST = 50
CLASS_UNLOCK_2_COST = 75

[WOTC_Prof_Warden_BD.X2Effect_WardenMeleeDamageFocus]
MELEEFOCUS_MAXIMUM_BONUS = 4

[WOTC_Prof_Warden_BD.X2Effect_WardenRangedDamageFocus]
FIREARMFOCUS_MAXIMUM_BONUS = 4

[WOTC_Prof_Warden_BD.X2Effect_WardenRetributionOverwatch]
+OverwatchAbilities=IRI_RN_Intercept
+OverwatchAbilities=IRI_Rider_Intercept
+OverwatchAbilities=ShadowOps_SnapShotOverwatch
+OverwatchAbilities=ShadowOps_ReadyForAnythingOverwatch
+OverwatchAbilities=SnapShotOverwatch
+OverwatchAbilities=LongWatch
+OverwatchAbilities=SniperRifleOverwatch
+OverwatchAbilities=Overwatch
+OverwatchAbilities=PistolOverwatch
